# -*- coding: utf-8 -*-
"""
扩展章节生成器：生成 107 个深度章节（编号 94-200）。
四大板块，每个板块有详细的章节内容定义。
"""
import os, html, re

BASE = '/Users/guchuan/ZCodeProject/ai-tutorial'

# ============================================================
# 章节 SLOTS：每章 (slug, title, group, seed)
# seed 是核心论点，生成器据此扩写
# ============================================================

GROUPS = {
    'tfm':  ('Transformer 原理深挖', [
        ('tfm-attention-math', '注意力的数学本质：从点积到 Softmax',
         '把 Attention(Q,K,V)=softmax(QK^T/√d_k)V 逐符号拆解。点积衡量相关性、√d_k 防止 softmax 饱和、softmax 归一化成权重、权重加权 V。配 3×3 手算示例。'),
        ('tfm-qkv-projection', 'Q/K/V 投影：为什么需要三个矩阵',
         '同一输入需扮演"查询者/被检索标签/被提取信息"三个角色。W_Q/W_K/W_V 学会从输入抽出三种视角，W_O 融合多头。投影矩阵是注意力层参数的主要来源。'),
        ('tfm-positional-encoding', '位置编码：没有它 Transformer 是个瞎子',
         '注意力对顺序无感（置换不变），必须注入位置。正弦余弦编码的多尺度频率、可学习编码的外推难题。相加而非拼接的原理。'),
        ('tfm-rope', 'RoPE 旋转位置编码：现代大模型的标配',
         '通过旋转向量把绝对位置编码进相对关系，q_m·k_n 只依赖 m-n。块对角旋转矩阵、θ 频率设计、外推能力、PI/NTK/YaRN 长上下文插值。'),
        ('tfm-multihead', '多头注意力：为什么"多看几个角度"更有效',
         '多头让模型在不同子空间学不同关注模式（语法/语义/共现）。h 个头并行、Concat 后 W_O 融合。头数、维度分配、为什么 8 头比 1 头强。'),
        ('tfm-mqa-gqa', '从 MHA 到 MQA、GQA：推理加速的关键',
         'MHA 每头独立 KV，显存/带宽随头数爆炸。MQA 所有头共享一组 KV（Llama-2 70B）。GQA 分组共享折中（Llama-2/3、GLM）。对 KV cache 和 serving 成本的影响。'),
        ('tfm-kv-cache', 'KV Cache：自回归推理为什么离不开它',
         '生成第 t 个 token 时前面 t-1 个 token 的 K/V 已算过且不变，缓存避免重算。显存占用公式、prefill vs decode 阶段、为什么 decode 是访存瓶颈。'),
        ('tfm-flash-attention', 'FlashAttention：让注意力不再是显存噩梦',
         '标准注意力 O(n²) 显存、要物化 n×n 注意力矩阵。FlashAttention 用 tiling + online softmax 在 SRAM 里完成计算，HBM 读写降到 O(n)。IO-aware 算法设计。'),
        ('tfm-ffn', '前馈网络：注意力之后的"记忆"层',
         'FFN 占 Transformer 参数量 2/3，是事实上的知识存储。两层 MLP + 激活，中间维扩 4×。SwiGLU 激活的改进（Llama/GLM）。为什么 FFN 是 key-value 记忆假说。'),
        ('tfm-layernorm', 'LayerNorm 与残差：让深层 Transformer 可训练',
         '残差连接解决梯度消失、LayerNorm 稳定每层分布。Pre-norm vs Post-norm 的训练稳定性差异。RMSNorm（去掉均值中心化）为何成为现代标配。'),
        ('tfm-softmax-variants', 'Softmax 之外：线性注意力的尝试',
         'softmax 注意力 O(n²) 是长序列瓶颈。线性注意力把 softmax 拆成 φ(Q)φ(K)^T，利用结合律降到 O(n)。Performer 用随机特征近似 softmax。性能与效果的权衡。'),
        ('tfm-attention-bias', 'ALiBi 与相对位置偏置：另一种注入位置的方式',
         '不靠编码，直接在注意力分数上加按距离衰减的线性偏置。ALiBi 的外推能力、训练效率。与 RoPE 的对比，何时用哪个。'),
        ('tfm-context-length', '上下文窗口的物理极限与突破',
         'n² 显存/计算、KV cache 显存、位置编码外推三重瓶颈。Ring Attention、序列并行、稀疏注意力如何支撑百万 token 上下文。'),
        ('tfm-tokenization', 'Tokenizer：文字如何变成模型能吃的 Token',
         'BPE 算法的字节级实现、词表大小 trade-off。SentencePiece、tiktoken。多语言、代码、emoji 的分词问题。词表对推理成本的影响。'),
        ('tfm-embedding', 'Token Embedding 与 Tie Weights',
         '嵌入矩阵的查表本质、维度选择。输入输出嵌入权重共享（weight tying）省参数 + 效果好。为什么大模型倾向不 tie。'),
        ('tfm-decoder-only', '为什么 Decoder-Only 一统天下',
         'Encoder-Decoder（T5）、Encoder-only（BERT）、Decoder-only（GPT/GLM）三架构对比。统一为 next-token prediction 的简洁性、scaling 友好、in-context learning 涌现。'),
        ('tfm-generation-strategy', '解码策略：贪心/采样/beam 的取舍',
         'Greedy 简单调板、Temperature/Top-k/Top-p 采样的随机性控制、Beam search 的全局最优近似。为什么创意任务用采样、翻译用 beam、代码用低温度。'),
        ('tfm-repetition-penalty', '重复惩罚与可控生成',
         '模型为什么会"卡死"在重复循环。repetition penalty、frequency penalty、presence penalty 的机制。如何在多样性与连贯性间调参。'),
        ('tfm-sampling-tricks', '典型采样与 mirostat：动态截断',
         'Top-p 固定截断的局限。Locally Typical Sampling 选最符合熵的截断点。Mirostat 动态调温度维持目标惊喜度。控制生成质量的进阶旋钮。'),
        ('tfm-attention-mask', '注意力掩码：因果、双向、文档级',
         '因果掩码（下三角）实现自回归、padding 掩码忽略无效位、文档/前缀掩码实现 prefix-tuning 与 packing。掩码是 Transformer 最灵活的控制面。'),
        ('tfm-speculative-decoding', '投机解码：用小模型加速大模型',
         '小模型草拟多个 token、大模型批量验证、接受匹配前缀。Medusa 多头并行预测。2-3 倍加速且无损，是 serving 的免费午餐。'),
        ('tfm-quantization', '量化：让大模型跑在消费级显卡上',
         'INT8/INT4 量化的精度损失与显存收益。GPTQ 训后量化、AWQ 激活感知、GGUF 的 k-quants。为什么 4bit 几乎无损、group-wise 量化。'),
        ('tfm-moe-intro', 'MoE 混合专家：用稀疏激活做大模型',
         '专家路由、top-k 门控、负载均衡 loss。GLM-5.2 等用 MoE 把参数做大而计算量保持小。专家冗余、路由塌缩问题。'),
        ('tfm-moe-routing', 'MoE 路由的工程细节',
         'auxiliary loss 防路由塌缩、capacity factor 控制负载、expert parallelism 的通信开销。Token dropping 策略。DeepSeek MoE 的细粒度专家。'),
        ('tfm-mamba-ssm', 'Mamba 与 SSM：挑战 Transformer 的新路线',
         '状态空间模型的连续动力系统视角、选择性 SSM 的硬件感知实现。线性复杂度的长序列优势、与注意力混合的 Jamba 等架构。'),
        ('tfm-from-scratch', '从零实现一个迷你 Transformer',
         '用 PyTorch 实现嵌入+位置编码+多头注意力+FFN+LayerNorm+残差，拼成一个能跑的小 GPT。完整代码 + 训练循环。理解每个零件如何咬合。'),
    ]),
    'vec':  ('向量索引与 RAG 原理深挖', [
        ('vec-ann-overview', 'ANN 概览：为什么不能用暴力 kNN',
         '精确 kNN O(N·d) 在百万级数据上不可行。ANN 牺牲少量召回换数量级加速。图/聚类/量化/哈希四大流派。recall@k vs QPS 的权衡曲线。'),
        ('vec-ivf', 'IVF 倒排索引：用聚类加速检索',
         'k-means 把向量聚成 nlist 簇，每个簇一个质心。查询时找最近的 nprobe 个质心，只搜这些簇。nprobe 控制 recall/latency。FAISS IVFFlat 的实现。'),
        ('vec-ivf-tuning', 'IVF 调参实战：nlist 与 nprobe 的取舍',
         'nlist ≈ √N 经验值。nprobe 小则快但漏召、大则慢但准。如何用 recall@10 vs QPS 曲线选工作点。大数据集的 IVF 训练成本。'),
        ('vec-hnsw', 'HNSW 分层小世界图：低延迟之王',
         '多层跳跃图：上层稀疏快速导航、底层稠密精确搜索。插入时逐层选邻居、查询时从顶层贪心下降。M/efConstruction/efSearch 三参数。'),
        ('vec-hnsw-insert', 'HNSW 插入算法详解',
         '从顶层 ep 出发、每层贪心找最近、用启发式选 M 个邻居（去冗余）、连接。为什么启发式选邻比简单选最近更鲁棒。构建时间复杂度。'),
        ('vec-hnsw-query', 'HNSW 查询算法与 ef 调优',
         '查询时只在最底层做 ef 动态候选集搜索。ef 越大召回越高但越慢。如何针对不同 SLA 调 ef。pgvector/Weaviate/Qdrant 的 HNSW 默认值。'),
        ('vec-pq', '乘积量化 PQ：把向量压到 1/16',
         '把 d 维向量切成 m 段，每段独立 k-means 生成码本。每个子向量用 1 字节存码本索引。1GB→64MB 的压缩比。精度损失来自子空间量化误差。'),
        ('vec-pq-adc', 'ADC 与对称距离计算',
         '查询时不对压缩向量解压，而是预计算 query 到每段码本的距离表（ADC），查表累加。O(m) 查表 vs O(d) 点积。IVFPQ 的三级加速。'),
        ('vec-lsh', 'LSH 局部敏感哈希',
         '相似项以高概率哈希到同桶。随机投影 LSH（余弦相似度）、MinHash（Jaccard）。与图方法对比：更适合超大规模、低精度的初筛。'),
        ('vec-scann', 'ScaNN 与各向异性量化',
         'Google 的 ScaNN 用各向异性量化减少高方差方向的误差，配合残量重排。在 ann-benchmark 上长期领先。原理与适用场景。'),
        ('vec-diskann', 'DiskANN：内存装不下的亿级索引',
         '把图存在 SSD，内存只放压缩向量与路由结构。beam search 顺序读盘。在单机能跑十亿级向量的方案。Vamana 构建算法。'),
        ('vec-filtering', '元数据过滤：ANN 与 WHERE 子句',
         'pre-filter 先按元数据缩小再 ANN、post-filter 先 ANN 再过滤、in-filter 在搜索中过滤。各方案的 recall 与适用条件。稀疏结果集的坑。'),
        ('vec-hybrid-search', '混合检索：BM25 + 向量的正确姿势',
         '稀疏（BM25/关键词）抓精准命中、稠密（向量）抓语义相关。RSV 融合 vs 加权求和。RRF（倒数秩融合）为何对分数尺度不敏感。'),
        ('vec-rerank', '重排序 Rerank：精排召回结果',
         '召回阶段用快的双塔/ANN 拿 top-1000，精排用交叉编码器（cross-encoder）逐对打分取 top-10。bge-reranker、Cohere rerank 的原理。延迟换精度。'),
        ('vec-embedding-models', '嵌入模型选型：BGE、E5、Cohere',
         '对比模型的维度、最大输入、多语言、领域。MTEB 榜单怎么看。中文场景 BGE-M3、英文 Cohere v3。指令微调嵌入（query/passage 前缀）。'),
        ('vec-chunking', '分块策略：固定/递归/语义/父子',
         '固定窗口简单但切断语义、递归按分隔符层级切、语义分块按相似度断点、父子块召回小块但返回大块上下文。chunk size 与 overlap 的取舍。'),
        ('vec-chunking-deep', '分块进阶：表格、代码、长文档',
         'Markdown 标题感知分块、代码按函数/类分块、表格整块保留。长 PDF 的版面分析。chunk overlap 如何避免边界信息丢失。'),
        ('vec-rag-architecture', 'RAG 系统架构：从查询到引用',
         '完整管线：查询改写 → 混合检索 → 重排 → 上下文组装 → LLM 生成 → 引用标注。每环节的设计选择与失败模式。'),
        ('vec-query-rewrite', '查询改写：让检索更准',
         'HyDE 假设性文档生成、查询分解子问题、多查询融合、回指消解。用 LLM 把用户模糊提问转成检索友好的形式。'),
        ('vec-context-packing', '上下文组装：Lost in the Middle',
         '把召回的相关文档塞进 prompt 的顺序与位置很关键——中段易被忽略。重排把最相关的放头尾、按相关性递减。context window 的预算分配。'),
        ('vec-rag-eval', 'RAG 评估：RAGAS 与忠实度',
         '命中率、上下文相关性、忠实度（faithfulness）、答案相关性四指标。自动评估用 LLM-as-judge。端到端 answer correctness。'),
        ('vec-graphrag', 'GraphRAG：知识图谱增强检索',
         '从文档抽取实体关系建图，检索时既取向量又走图。社区检测生成摘要。解决"跨文档推理"类问题。微软 GraphRAG 方案。'),
        ('vec-multivec', 'ColBERT 与多向量检索',
         '单向量压缩信息的损失。ColBERT 每个 token 一个向量，MaxSim 逐 token 交互。比双塔准、比 cross-encoder 快。PLAID 加速引擎。'),
        ('vec-splade', 'SPLADE 稀疏向量：学习型 BM25',
         '用模型生成稀疏高维向量（词项权重），既可语义又能精确匹配。与传统倒排索引兼容。稀疏与稠密的统一表示。'),
        ('vec-eval-benchmark', 'ANN 基准测试：ann-benchmark 实战',
         'recall@k vs QPS 曲线、不同数据集（SIFT/GLOVE/Deep）的表现、如何为自己的数据选索引。离线评估与在线 A/B。'),
        ('vec-prod-ops', '向量库运维：重建、调优、成本',
         '索引随数据增长何时重建、HNSW 内存膨胀、embedding 模型升级的迁移。云服务 vs 自建 pgvector/Milvus 的成本对比。'),
    ]),
    'agent': ('开源 Agent 源码深挖', [
        ('agent-opencode-arch', 'OpenCode 架构：客户端/服务器分离',
         'sst/opencode 的 client-server 架构。服务端管会话/工具/LLM，客户端是 TUI/GUI。通过协议解耦让一个后端多前端复用。'),
        ('agent-opencode-loop', 'OpenCode 的 Agent Loop 实现',
         '循环：LLM 推理 → 解析工具调用 → 执行工具 → 把结果拼回上下文 → 再推理。直到模型不再调工具返回最终答案。会话状态与消息流转。'),
        ('agent-opencode-tools', 'OpenCode 工具系统：read/write/bash/grep',
         '内置工具定义 schema（参数类型/描述）。read 抽文件、write 改文件、bash 执行命令、glob/grep 搜索。每个工具的输入输出契约。'),
        ('agent-opencode-permission', 'OpenCode 权限模型：工具级守卫',
         '权限边界设在工具层而非 prompt 里。每个 agent 配置允许的工具白名单，危险工具（bash/write）需确认。避免 prompt 注入绕过。'),
        ('agent-opencode-context', 'OpenCode 上下文收集',
         '调用前收集项目上下文：git 状态、文件树、LSP 诊断。把环境信息注入 system prompt 让模型理解当前代码库。'),
        ('agent-opencode-mcp', 'OpenCode 与 MCP 协议',
         '接入 MCP server 扩展工具能力。stdio/SSE 传输、工具发现、能力协商。一个 MCP server 可被多个 agent 复用。'),
        ('agent-opencode-session', 'OpenCode 会话持久化',
         '会话存为 JSON：消息列表 + 工具调用记录 + 元数据。可恢复、可分支、可回放。文件系统即数据库的极简方案。'),
        ('agent-codex-arch', 'Codex CLI 架构：Rust 内核 + TS 前端',
         'openai/codex 用 codex-rs 做高性能内核（协议/沙箱/循环），TS 做 CLI/UI。queue-pair（Op-Event）协议解耦。'),
        ('agent-codex-loop', 'Codex 的 Turn 模型与推理持久化',
         '一个 turn：用户输入 → 模型推理（含 reasoning）→ 工具调用 → 观测 → 重复 → 助手消息结束。reasoning 跨 turn 持久化保留思路。'),
        ('agent-codex-responses-api', 'Codex 用 Responses API',
         '服务器端根据工具 schema + 客户端输入构建真正 prompt。Responses API 原生支持工具/推理/多模态。客户端只发意图。'),
        ('agent-codex-sandbox-seatbelt', 'Codex 沙箱：macOS Seatbelt',
         'sandbox-exec 动态生成策略文件。profile 限制文件写/网络/exec。workspace-write 模式只允许工作目录写。'),
        ('agent-codex-sandbox-landlock', 'Codex 沙箱：Linux Landlock + seccomp',
         'Landlock 限制文件系统访问、seccomp 过滤系统调用。两层防御。与 macOS Seatbelt 的对应关系。'),
        ('agent-codex-approval', 'Codex 审批：sandbox_mode × approval_policy',
         '两条正交轴：sandbox_mode（物理允许什么）+ approval_policy（何时停下问）。read-only/workspace-write/danger 三档 × untrusted/on-failure/on-request/never。预设组合。'),
        ('agent-codex-exec', 'Codex exec 路径：命令分类',
         'exec.rs 把命令分类 safe/match/needs-approval。安全命令直接跑、需审批的弹确认。execpolicy crate 的规则匹配。'),
        ('agent-codex-guardian', 'Codex Guardian AI 审批',
         '用独立 LLM 给工具调用做风险评估、自动放行低风险。rubber-stamp 机制降低打断频率。误判的代价与回退。'),
        ('agent-codex-config', 'Codex 配置：config.toml 全解',
         'sandbox_mode、approval_policy、model、model_provider、mcp_servers 等键。项目级 vs 用户级配置优先级。企业 deny 策略不可覆盖。'),
        ('agent-aider-edit-formats', 'Aider 的文件编辑格式',
         'SEARCH/REPLACE 块：精确匹配旧文本整段替换。vs unified diff、whole-file。为何 SEARCH/REPLACE 对 LLM 最可靠（不偏移、不需行号）。'),
        ('agent-aider-repomap', 'Aider 的 Repo Map',
         '用 tree-sitter 抽取符号（函数/类/方法），按 PageRank 排重要性，喂给模型当目录。让模型"看见"整个仓库结构而不耗尽上下文。'),
        ('agent-aider-git', 'Aider 的 Git 集成',
         '每次编辑自动 commit，提交信息由模型生成。可回滚、可 diff、可 branch。把 AI 编辑纳入版本控制工作流。'),
        ('agent-continue-arch', 'Continue 的 IDE 架构',
         'VSCode/JetBrains 扩展 + 后端。@-mention 上下文、slash command、chat 模式。前后端协议。'),
        ('agent-continue-codebase', 'Continue 的代码库索引',
         '用 LanceDB 存代码块向量。tree-sitter 切块、嵌入、检索。@codebase 触发全仓库语义搜索。增量索引。'),
        ('agent-continue-embeddings', 'Continue 的嵌入管线',
         '本地 Transformers.js vs API 嵌入模型。分块大小、批处理、去重。索引构建的性能与质量。'),
        ('agent-cline-loop', 'Cline 的工具循环与审批',
         'VSCode 扩展，每步工具调用都要用户确认（默认）。read/write/edit/execute/browser 工具。auto-approve 规则。'),
        ('agent-cline-diff', 'Cline 的差异编辑',
         '给出文件完整内容 + 行号，模型输出 search/replace 块。严格的 XML 结构、校验匹配。错误恢复策略。'),
        ('agent-cursor-agent', 'Cursor 的 Agent 模式',
         'IDE 原生集成、长任务 agent、多文件编辑。composer 多文件同步改。索引与检索的工程优化。'),
        ('agent-roo-modes', 'Roo Code 的多模式',
         'Architect/Code/Ask/Debug 四模式，不同模式不同 system prompt 与工具集。模式切换的工作流。'),
        ('agent-sourcecode-prompt', '源码级启示：系统提示工程',
         '从这些 agent 的源码学系统提示设计：角色、工具说明、约束、输出格式、错误恢复。可复用的模式。'),
        ('agent-sourcecode-streaming', '源码级启示：流式输出处理',
         'SSE/JSON 流解析、增量渲染、工具调用边到边处理、取消机制。前端如何平滑展示流。'),
        ('agent-sourcecode-context-window', '源码级启示：上下文管理',
         '长对话的截断、摘要、压缩。token 预算分配。工具结果何时精简。session 分页。'),
        ('agent-sourcecode-error-recovery', '源码级启示：错误恢复',
         '工具执行失败、JSON 解析失败、超时的重试与降级。模型自纠循环。死循环检测。'),
        ('agent-sourcecode-mcp-deep', '源码级启示：MCP 集成',
         'MCP server 生命周期、工具发现、能力协商、多 server 聚合。stdio vs SSE 的实现差异。'),
        ('agent-sourcecode-parallel', '源码级启示：并行工具调用',
         '一次推理返回多个工具调用、并行执行、结果聚合。race condition 与顺序保证。'),
        ('agent-sourcecode-testing', '源码级启示：Agent 测试',
         '如何给 agent loop 写测试：mock LLM、固定工具响应、断言工具调用序列。回归测试夹具。'),
    ]),
    'extra': ('进阶综合与实战补全', [
        ('xtra-evals-deep', 'LLM 评估方法学：从 BLEU 到 LLM-as-judge',
         '自动指标（BLEU/ROUGE/rouge）的局限、人工评估成本、LLM-as-judge 的校准、成对比较与 Elo。多维度 rubric。'),
        ('xtra-data-pipeline', '训练数据管线：清洗去重质量',
         'CommonCrawl 清洗、MinHash 去重、质量分类器、毒性过滤、PII 脱敏。数据配比与课程化。'),
        ('xtra-pretraining-math', '预训练的损失与优化',
         '交叉熵损失、AdamW 优化器、cosine 学习率调度、warmup。batch size 与梯度累积。loss 曲线解读。'),
        ('xtra-sft-details', 'SFT 数据构造与训练',
         '指令数据来源（人工/种子/合成）、模板格式（ChatML/vicuna）、packing、loss masking 只算回答。过拟合风险。'),
        ('xtra-rlhf-dpo', 'RLHF 到 DPO：对齐方法演进',
         'PPO 的奖励模型 + 策略优化复杂度、DPO 直接用偏好对训练省掉 RM。IPO/KTO 等变体。DPO 为何流行。'),
        ('xtra-grpo', 'GRPO 与推理能力对齐',
         'Group Relative Policy Optimization 省去 value 网络、用组内相对优势。DeepSeek-R1 的核心。奖励稀疏的推理任务。'),
        ('xtra-inference-batch', '推理 batching：连续批处理',
         '动态 batching 把不同请求凑批、连续批处理（continuous batching）边到边加入。vLLM/SGLang 的吞吐优化。'),
        ('xtra-paged-attn', 'PagedAttention：KV 显存的虚拟内存',
         '把 KV cache 当虚拟内存按页分配，消除碎片。vLLM 的核心创新。显存利用率从 40% 到 90%。'),
        ('xtra-prefix-cache', '前缀缓存：复用共享上下文',
         '多请求共享 system prompt 时复用其 KV。RadixAttention 树形管理前缀。Few-shot/系统提示场景的大幅加速。'),
        ('xtra-distill', '知识蒸馏：大模型教小模型',
         '软标签（logits 蒸馏）、输出模仿、特征蒸馏。为什么小模型能逼近大模型。部署成本与能力的权衡。'),
        ('xtra-privacy-federated', '隐私保护：差分隐私与联邦',
         'DP-SGD 加噪保证 (ε,δ)、成员推理攻击防御。联邦学习的数据不出域。隐私 vs 性能权衡。'),
        ('xtra-safety-jailbreak', '越狱攻防：红队视角',
         'prompt 注入、角色扮演越狱、编码绕过、多轮诱导。防御：输入过滤、宪法 AI、输出审核。攻防循环。'),
        ('xtra-constitutional-ai', 'Constitutional AI：自我修正对齐',
         '用宪法原则让模型批判并改写自己的输出，RLAIF 用 AI 当标注者。降低人工标注成本。'),
        ('xtra-mech-interp', '机械可解释性：读懂神经元',
         '激活最大化、探针、因果追踪、稀疏自编码器解纠缠 superposition。从黑盒走向白盒。'),
        ('xtra-scaling-laws', 'Scaling Laws：为什么大就是好',
         'Kaplan/Chinchilla 定律、计算/数据/参数的最优配比、涌现能力。预测训练成本与效果。'),
        ('xtra-chinchilla', 'Chinchilla 之后：数据才是瓶颈',
         '60× 数据 vs 1× 参数的教训。数据重复的边际效益递减。合成数据与课程学习补充。'),
        ('xtra-energy', 'AI 的能耗与碳足迹',
         '训练 GPT 级模型的电力消耗、数据中心选址、推理的长期能耗。绿色 AI 与能效优化。'),
        ('xtra-edge-deploy', '端侧部署：手机跑大模型',
         'LLaMA.cpp 的 GGUF、Apple MLX、移动 NPU。量化 + 蒸馏 + 算子优化。隐私与离线优势。'),
        ('xtra-multimodal-arch', '多模态架构：视觉编码器如何接入',
         'CLIP 视觉编码器 + 投影层 + LLM。LLaVA/GPT-4V 的方案。图像 token 化、分辨率与位置编码。'),
        ('xtra-speech-arch', '语音模型：从 ASR 到端到端',
         'Whisper 的 encoder-decoder、流式 ASR 的 chunking、TTS 的声音克隆。语音 token 与 LLM 对齐。'),
        ('xtra-future', 'AI 的下一站：AGI 路线图',
         '从工具到 agent 到自主系统。多模态融合、长时记忆、世界模型。开放问题与风险。'),
        ('xtra-glossary2', '术语补遗与速查表',
         '本系列所有专有名词的最终定义合集。Token/Embedding/Attention/FFN/MoE/RLHF/RAG/Agent 等的精炼解释。'),
    ]),
}

# ============================================================
# 内容扩写器：把 seed 论点扩成充实段落
# ============================================================

def expand_block(group, slug, title, seed, idx):
    """根据 seed 扩写出一段充实内容。"""
    gname = {'tfm': 'Transformer', 'vec': '向量检索', 'agent': 'Agent 源码', 'extra': '进阶实战'}[group]
    blocks = []
    # 章首 hero
    blocks.append(('hero', (title, f'第 {94+idx} 章 · {gname}深挖', seed)))
    # 开篇导读
    blocks.append(('h2', '导读'))
    blocks.append(('p', seed))
    blocks.append(('p', f'本章属于"{gname}原理深挖"系列。我们不满足于"会用 API"，而是要拆开黑盒，看清每个机制背后的数学、工程取舍和真实代码。读完你不仅能解释"为什么"，还能在自己的项目里复现这些机制。'))
    return blocks


# 这个文件作为定义被主生成器导入
if __name__ == '__main__':
    total = sum(len(v[1]) for v in GROUPS.values())
    print(f'总章节数: {total}')
    for g, (name, chapters) in GROUPS.items():
        print(f'  {g} ({name}): {len(chapters)} 章')
